@api = http://localhost:5000

# obtener todas las tareas
GET {{api}}/user/patients

# creando un usuario NO MEDICO
POST {{api}}/user/signup
Content-Type: application/json

{
    "userID": "TueJan182000CristhianWiki",
    "dateOfBirth": "2000-01-18T05:00:00.000+00:00",
    "direction": "Comas",
    "email": "user@gmail.com",
    "hospital": "",
    "isMedic": "false",
    "lastUse": "2021-07-02T01:26:59.687+00:00",
    "name":"Cristhian Wiki",
    "password": "user98",
    "profileImage": "",
    "speciality": "",
    "timeContract": ""
}

# creando un usuario MEDICO
POST {{api}}/user/signup
Content-Type: application/json

{
    "userID": "ThuOct211999RonaldoCampos",
    "dateOfBirth": "1999-10-21T05:00:00.000+00:00",
    "direction": "Comas",
    "email": "medic@gmail.com",
    "hospital": "Rezola",
    "isMedic": "true",
    "lastUse": "2021-07-02T01:27:19.952+00:00",
    "name": "Ronaldo Campos",
    "password": "medic98",
    "profileImage": "",
    "speciality": "Dermatología",
    "timeContract": "Indefinido"
}


//LOGIN
POST {{api}}/user/signin
Content-Type: application/json

{
    "email": "medic@gmail.com",
    "password":"medic98"
}


// CREAR ESTADÍSTICA
POST {{api}}/stadistic/register
Content-Type: application/json

{
    "medicID":  "ThuOct211999RonaldoCampos",
    "disponibility": "10",
    "demandability": "20",
    "expertise": "70",
    "successPatientsID": "",
    "waitingPatientsID": "TueJan182000CristhianWiki"
}

// ACTUALIZAR ESTADÍSTICA
POST {{api}}/stadistic/update
Content-Type: application/json

{
    "medicID":  "ThuOct211999RonaldoCampos",
    "disponibility": "30",
    "demandability": "40",
    "expertise": "70",
    "successPatientsID": "TueJan182000CristhianWiki",
    "waitingPatientsID": ""
}

//CREAR HISTORIAL
POST {{api}}/history/register
Content-Type: application/json

{
    "patientID": "TueJan182000CristhianWiki",
    "diagnosisID":  ""
}

//ACTUALIZAR HISTORIAL
POST {{api}}/history/update
Content-Type: application/json

{
    "patientID": "TueJan182000CristhianWiki",
    "diagnosisID":  "diagnosis_TueJan182000CristhianWiki_TueJan182000CristhianWiki"
}

// CREAR DIAGNÓSTICO (el diagnóstico debe estar en
// en la colección Historial)
POST {{api}}/diagnosis/register
Content-Type: application/json

{
    "diagnosisID":  "diagnosis_TueJan182000CristhianWiki_TueJan182000CristhianWiki",
    "textDiagnosis": "Leve lesión cerebral en la zona parietal",
    "imageDiagnosis": "soy una imagen codificada en 64bits",
    "dateOfDiagnosis": "2000-01-01T05:00:00.000Z",
    "medicValidatorID": ""
}

// OBTENER DIAGNÓSTICO INDIVIDUAL
GET {{api}}/diagnosis/lastDiagnosis?patientID=TueJan182000CristhianWiki

// ACTUALIZAR DIAGNÓSTICO
POST {{api}}/diagnosis/update
Content-Type: application/json

{
    "diagnosisID":  "diagnosis_TueJan182000CristhianWiki_TueJan182000CristhianWiki",
    "textDiagnosis": "Leve lesión cerebral en la zona parietal GRAVE",
    "imageDiagnosis": "soy una imagen codificada en 64bits",
    "dateOfDiagnosis": "2000-01-01T05:00:00.000Z",
    "medicValidatorID": "ThuOct211999RonaldoCampos"
}

// DESCARGAR PDF
GET {{api}}/diagnosis/downloadPDF?patientID=TueJan182000CristhianWiki&patientName=Cristhian%20Wiki&patientAge=20